---
- name: Testing andrewrothstein.vcluster
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'vcluster --version'
      ansible.builtin.command: /usr/local/bin/vcluster --version
      changed_when: false
      register: vcluster_test_output
    - name: Output of 'vcluster --version'
      ansible.builtin.debug:
        msg: '{{ vcluster_test_output.stdout }}'
