---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_facts["distribution"] }}-{{ ansible_facts["distribution_release"] }}.yml'
        - '{{ ansible_facts["distribution"] }}.yml'
        - '{{ ansible_facts["os_family"] }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Downloading {{ vcluster_url }} to {{ vcluster_install_exe }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ vcluster_url }}'
    dest: '{{ vcluster_install_exe }}'
    checksum: '{{ vcluster_checksum }}'
    mode: '755'
- name: Linking {{ vcluster_link }} to {{ vcluster_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ vcluster_install_exe }}'
    dest: '{{ vcluster_link }}'
    state: link
